version: '3.8'
services:
  jenkins:
    image: alpine/socat
    container_name: docker-agent
    restart: always
    ports:
      - 2376:2375
      - target: 2376
        published: 2375
        protocol: tcp

    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - learn-jenkins-jenkins
    environment:
      - DOCKER_HOST=tcp://docker:2375
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1

volumes:
  jenkins_home: